name:                ch3
version:             0.1.0.0
github:              "githubuser/ch3"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ch3#readme>

dependencies:
- base >= 4.7 && < 5
- yapb >= 0.2.3
- hspec
- containers

library:
  source-dirs: 
   - src

executables:
  letlang-exe:
    main:                Main.lhs
    source-dirs:         
    - app/letlang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch3

  proclang-exe:
    main:                Main.lhs
    source-dirs:         
    - app/proclang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch3

  letreclang-exe:
    main:                Main.lhs
    source-dirs:         
    - app/letreclang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch3

  rpclang-exe:
    main:                Main.hs
    source-dirs:         
    - app/rpclang
    - app/rpclang/actors
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch3

tests:
  letlang-test:
    main:                Spec.hs
    source-dirs:         
    - test/letlang
    - app/letlang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch3

  proclang-test:
    main:                Spec.hs
    source-dirs:         
    - test/proclang
    - app/proclang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch3

  letreclang-test:
    main:                Spec.hs
    source-dirs:         
    - test/letreclang
    - app/letreclang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch3

  rpclang-test:
    main:                Spec.hs
    source-dirs:         
    - test/rpclang
    - app/rpclang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch3